config/routes.rb
Rails.application.routes.draw do
  root 'doctors#index'

  resources :appointments, only: [:index]
  resources :doctors, only: [:show] do
    resources :appointments, only: [:index, :create]
  end

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  validates :patient, :doctor, :starts_at, :ends_at, presence: true
  belongs_to :doctor
  validate :starts_at_after_ends_at, if: Proc.new { |appointment| appointment.ends_at && appointment.starts_at }
  validate :no_conflicting_appointments, if: Proc.new { |appointment| appointment.doctor }
  scope :during, ->(starts_at, ends_at) { where("starts_at <= :ends_at and ends_at >= :starts_at",{:ends_at => ends_at, :starts_at => starts_at}) }

  def starts_at_after_ends_at
    errors.add(:ends_at, "can't be before starts at") if ends_at < starts_at
  end

  def no_conflicting_appointments
    errors.add(:base, "#{self.doctor.name} already has an appointment during that time") if doctor.appointments.during(starts_at, ends_at).any?
  end

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def index
    date = if params[:date]
      params[:date]
    else
      Date.today
    end
    starts_at = date.to_datetime
    ends_at = starts_at + 1
    if params[:doctor_id]
      doctor = Doctor.find_by(id: params[:doctor_id])
      render json: doctor.appointments.during(starts_at, ends_at), :include => {:doctor => {:only => :name}}
    else
      render json: Appointment.during(starts_at, ends_at), :include => {:doctor => {:only => :name}}
    end
  end

  def create
    doctor = Doctor.find_by(id: params[:doctor_id])
    appointment = doctor.appointments.new(appointment_params)
    if appointment.save
      render json: appointment
    else
      render json: appointment.errors.full_messages, status: 500
    end
  end

  private

  def appointment_params
    params.require(:appointment).permit(:doctor_id, :patient, :starts_at, :ends_at)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :load_doctors

  def show
    @appointment = Appointment.new
    @doctor = Doctor.find_by(id: params[:id])
  end

  private
  def load_doctors
    @doctors = Doctor.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/index.html.erb
<div id="calendar" class="all-doctors"></div>

app/views/doctors/show.html.erb
<h3 class="center-text"><%= @doctor.name %></h3>

<div class="form-wrapper center">
	<div class="inner-form-wrapper center blue">
		<h4 class="center-text">Schedule a new appointment</h4>
		<div id="appointment-errors" class="errors"></div>
		<%= form_for [@doctor, @appointment] do |f|%>
			<div class="input-wrapper">
				<div>
					<%= f.label :patient %>
				</div>
				<div>
					<%= f.text_field :patient %>
				</div>
			</div>
			<div class="input-wrapper">
				<div>
					<%= f.label :starts_at %>
				</div>
				<div>
					<%= f.datetime_select :starts_at, :discard_seconds => true %>
				</div>
			</div>
			<div class="input-wrapper">
				<div>
					<%= f.label :ends_at%>
				</div>
				<div>
					<%= f.datetime_select :ends_at, :discard_seconds => true %>
				</div>
			</div>
			<div class="input-wrapper">
				<%= f.submit %>
			</div>
		<% end %>
	</div>
</div>

<div id="calendar" class="one-doctor"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appoint A Doc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<div id="nav-wrapper" class="center-text blue">
		<h2 id="logo"><%= link_to "Appoint A Doc", root_path %></h2>
		<button class="hamburger">&#9776;</button>
		<button class="cross">&#735;</button>
		<div class="clear-fix"></div>
		<ul id="navbar">
			<% @doctors.each do |doctor| %>
				<li><%= link_to doctor.name, doctor_path(doctor)%></li>
			<% end %>
		</ul>

	</div>

	<div id="main">
		<%= yield %>
	</div>
	<div class="clear-fix"></div>
</div>
</body>
</html>